[package]
name = "bc_signals"
version = "0.2.1"
edition = "2024"

[dependencies]
bc_utils_lg = {path = "../bc_utils_lg"}
bc_utils = {path = "../bc_utils"}

dyn-clone = "1"

[dev-dependencies]
bc_test_kit = {path = "../bc_test_kit"}

criterion = {version = "0.8", features = ["html_reports"]}
pretty_assertions = "1"

[[bench]]
name = "change_signal"
harness = false
path = "benches/change_signal.rs"

[[bench]]
name = "change_src"
harness = false
path = "benches/change_src.rs"

[[bench]]
name = "convert"
harness = false
path = "benches/convert.rs"

 [[bench]]
name = "filter"
harness = false
path = "benches/filter.rs"

 [[bench]]
name = "invert"
harness = false
path = "benches/invert.rs"

 [[bench]]
name = "set_probability"
harness = false
path = "benches/set_probability.rs"

 [[bench]]
name = "th"
harness = false
path = "benches/th.rs"

[[bench]]
name = "copy"
harness = false
path = "benches/copy.rs"

[[bench]]
name = "repeat"
harness = false
path = "benches/repeat.rs"